CREATE DATABASE IF NOT EXISTS tickets2goApp CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE tickets2goApp;

CREATE TABLE IF NOT EXISTS waitlist_subscriptions (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(320) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_waitlist_email (email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
